config/routes.rb
Rails.application.routes.draw do
  resources :registration_form1s
  resources :registration_form_nikis
  resources :registration_formtests
  resources :registration_form_test_abcs
  resources :registration_forms
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/registration_form_test_abc.rb
class RegistrationFormTestAbc < ApplicationRecord
end

app/controllers/registration_form_test_ab_cs_controller.rb
class RegistrationFormTestAbCsController < ApplicationController
  before_action :set_registration_form_test_abc, only: [:show, :edit, :update, :destroy]

  # GET /registration_form_test_abcs
  # GET /registration_form_test_abcs.json
  def index
    @registration_form_test_abcs = RegistrationFormTestAbc.all
  end

  # GET /registration_form_test_abcs/1
  # GET /registration_form_test_abcs/1.json
  def show
  end

  # GET /registration_form_test_abcs/new
  def new
    @registration_form_test_abc = RegistrationFormTestAbc.new
  end

  # GET /registration_form_test_abcs/1/edit
  def edit
  end

  # POST /registration_form_test_abcs
  # POST /registration_form_test_abcs.json
  def create
    @registration_form_test_abc = RegistrationFormTestAbc.new(registration_form_test_abc_params)

    respond_to do |format|
      if @registration_form_test_abc.save
        format.html { redirect_to @registration_form_test_abc, notice: 'Registration form test abc was successfully created.' }
        format.json { render :show, status: :created, location: @registration_form_test_abc }
      else
        format.html { render :new }
        format.json { render json: @registration_form_test_abc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registration_form_test_abcs/1
  # PATCH/PUT /registration_form_test_abcs/1.json
  def update
    respond_to do |format|
      if @registration_form_test_abc.update(registration_form_test_abc_params)
        format.html { redirect_to @registration_form_test_abc, notice: 'Registration form test abc was successfully updated.' }
        format.json { render :show, status: :ok, location: @registration_form_test_abc }
      else
        format.html { render :edit }
        format.json { render json: @registration_form_test_abc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registration_form_test_abcs/1
  # DELETE /registration_form_test_abcs/1.json
  def destroy
    @registration_form_test_abc.destroy
    respond_to do |format|
      format.html { redirect_to registration_form_test_abcs_url, notice: 'Registration form test abc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registration_form_test_abc
      @registration_form_test_abc = RegistrationFormTestAbc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registration_form_test_abc_params
      params.require(:registration_form_test_abc).permit(:name, :phone)
    end
end

app/helpers/registration_form_test_ab_cs_helper.rb
module RegistrationFormTestAbCsHelper
end

app/views/registration_form_test_ab_cs/_form.html.erb
<%= form_with(model: registration_form_test_abc, local: true) do |form| %>
  <% if registration_form_test_abc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(registration_form_test_abc.errors.count, "error") %> prohibited this registration_form_test_abc from being saved:</h2>

      <ul>
      <% registration_form_test_abc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/registration_form_test_ab_cs/edit.html.erb
<h1>Editing Registration Form Test Abc</h1>

<%= render 'form', registration_form_test_abc: @registration_form_test_abc %>

<%= link_to 'Show', @registration_form_test_abc %> |
<%= link_to 'Back', registration_form_test_abcs_path %>

app/views/registration_form_test_ab_cs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registration Form Test Abcs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registration_form_test_abcs.each do |registration_form_test_abc| %>
      <tr>
        <td><%= registration_form_test_abc.name %></td>
        <td><%= registration_form_test_abc.phone %></td>
        <td><%= link_to 'Show', registration_form_test_abc %></td>
        <td><%= link_to 'Edit', edit_registration_form_test_abc_path(registration_form_test_abc) %></td>
        <td><%= link_to 'Destroy', registration_form_test_abc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registration Form Test Abc', new_registration_form_test_abc_path %>

app/views/registration_form_test_ab_cs/new.html.erb
<h1>New Registration Form Test Abc</h1>

<%= render 'form', registration_form_test_abc: @registration_form_test_abc %>

<%= link_to 'Back', registration_form_test_abcs_path %>

app/views/registration_form_test_ab_cs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @registration_form_test_abc.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @registration_form_test_abc.phone %>
</p>

<%= link_to 'Edit', edit_registration_form_test_abc_path(@registration_form_test_abc) %> |
<%= link_to 'Back', registration_form_test_abcs_path %>