config/routes.rb
Rails.application.routes.draw do
  resources :registration_form1s
  resources :registration_form_nikis
  resources :registration_formtests
  resources :registration_form_test_abcs
  resources :registration_forms
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/registration_formtest.rb
class RegistrationFormtest < ApplicationRecord
end

app/controllers/registration_formtests_controller.rb
class RegistrationFormtestsController < ApplicationController
  before_action :set_registration_formtest, only: [:show, :edit, :update, :destroy]

  # GET /registration_formtests
  # GET /registration_formtests.json
  def index
    @registration_formtests = RegistrationFormtest.all
  end

  # GET /registration_formtests/1
  # GET /registration_formtests/1.json
  def show
  end

  # GET /registration_formtests/new
  def new
    @registration_formtest = RegistrationFormtest.new
  end

  # GET /registration_formtests/1/edit
  def edit
  end

  # POST /registration_formtests
  # POST /registration_formtests.json
  def create
    @registration_formtest = RegistrationFormtest.new(registration_formtest_params)

    respond_to do |format|
      if @registration_formtest.save
        format.html { redirect_to @registration_formtest, notice: 'Registration formtest was successfully created.' }
        format.json { render :show, status: :created, location: @registration_formtest }
      else
        format.html { render :new }
        format.json { render json: @registration_formtest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registration_formtests/1
  # PATCH/PUT /registration_formtests/1.json
  def update
    respond_to do |format|
      if @registration_formtest.update(registration_formtest_params)
        format.html { redirect_to @registration_formtest, notice: 'Registration formtest was successfully updated.' }
        format.json { render :show, status: :ok, location: @registration_formtest }
      else
        format.html { render :edit }
        format.json { render json: @registration_formtest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registration_formtests/1
  # DELETE /registration_formtests/1.json
  def destroy
    @registration_formtest.destroy
    respond_to do |format|
      format.html { redirect_to registration_formtests_url, notice: 'Registration formtest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registration_formtest
      @registration_formtest = RegistrationFormtest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registration_formtest_params
      params.require(:registration_formtest).permit(:name, :phone)
    end
end

app/helpers/registration_formtests_helper.rb
module RegistrationFormtestsHelper
end

app/views/registration_formtests/_form.html.erb
<%= form_with(model: registration_formtest, local: true) do |form| %>
  <% if registration_formtest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(registration_formtest.errors.count, "error") %> prohibited this registration_formtest from being saved:</h2>

      <ul>
      <% registration_formtest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/registration_formtests/edit.html.erb
<h1>Editing Registration Formtest</h1>

<%= render 'form', registration_formtest: @registration_formtest %>

<%= link_to 'Show', @registration_formtest %> |
<%= link_to 'Back', registration_formtests_path %>

app/views/registration_formtests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registration Formtests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registration_formtests.each do |registration_formtest| %>
      <tr>
        <td><%= registration_formtest.name %></td>
        <td><%= registration_formtest.phone %></td>
        <td><%= link_to 'Show', registration_formtest %></td>
        <td><%= link_to 'Edit', edit_registration_formtest_path(registration_formtest) %></td>
        <td><%= link_to 'Destroy', registration_formtest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registration Formtest', new_registration_formtest_path %>

app/views/registration_formtests/new.html.erb
<h1>New Registration Formtest</h1>

<%= render 'form', registration_formtest: @registration_formtest %>

<%= link_to 'Back', registration_formtests_path %>

app/views/registration_formtests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @registration_formtest.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @registration_formtest.phone %>
</p>

<%= link_to 'Edit', edit_registration_formtest_path(@registration_formtest) %> |
<%= link_to 'Back', registration_formtests_path %>