config/routes.rb
Rails.application.routes.draw do
  resources :registration_form1s
  resources :registration_form_nikis
  resources :registration_formtests
  resources :registration_form_test_abcs
  resources :registration_forms
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/registration_form_niki.rb
class RegistrationFormNiki < ApplicationRecord
end

app/controllers/registration_form_nikis_controller.rb
class RegistrationFormNikisController < ApplicationController
  before_action :set_registration_form_niki, only: [:show, :edit, :update, :destroy]

  # GET /registration_form_nikis
  # GET /registration_form_nikis.json
  def index
    @registration_form_nikis = RegistrationFormNiki.all
  end

  # GET /registration_form_nikis/1
  # GET /registration_form_nikis/1.json
  def show
  end

  # GET /registration_form_nikis/new
  def new
    @registration_form_niki = RegistrationFormNiki.new
  end

  # GET /registration_form_nikis/1/edit
  def edit
  end

  # POST /registration_form_nikis
  # POST /registration_form_nikis.json
  def create
    @registration_form_niki = RegistrationFormNiki.new(registration_form_niki_params)

    respond_to do |format|
      if @registration_form_niki.save
        format.html { redirect_to @registration_form_niki, notice: 'Registration form niki was successfully created.' }
        format.json { render :show, status: :created, location: @registration_form_niki }
      else
        format.html { render :new }
        format.json { render json: @registration_form_niki.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registration_form_nikis/1
  # PATCH/PUT /registration_form_nikis/1.json
  def update
    respond_to do |format|
      if @registration_form_niki.update(registration_form_niki_params)
        format.html { redirect_to @registration_form_niki, notice: 'Registration form niki was successfully updated.' }
        format.json { render :show, status: :ok, location: @registration_form_niki }
      else
        format.html { render :edit }
        format.json { render json: @registration_form_niki.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registration_form_nikis/1
  # DELETE /registration_form_nikis/1.json
  def destroy
    @registration_form_niki.destroy
    respond_to do |format|
      format.html { redirect_to registration_form_nikis_url, notice: 'Registration form niki was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registration_form_niki
      @registration_form_niki = RegistrationFormNiki.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registration_form_niki_params
      params.require(:registration_form_niki).permit(:name, :phone)
    end
end

app/helpers/registration_form_nikis_helper.rb
module RegistrationFormNikisHelper
end

app/views/registration_form_nikis/_form.html.erb
<%= form_with(model: registration_form_niki, local: true) do |form| %>
  <% if registration_form_niki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(registration_form_niki.errors.count, "error") %> prohibited this registration_form_niki from being saved:</h2>

      <ul>
      <% registration_form_niki.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/registration_form_nikis/edit.html.erb
<h1>Editing Registration Form Niki</h1>

<%= render 'form', registration_form_niki: @registration_form_niki %>

<%= link_to 'Show', @registration_form_niki %> |
<%= link_to 'Back', registration_form_nikis_path %>

app/views/registration_form_nikis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registration Form Nikis</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registration_form_nikis.each do |registration_form_niki| %>
      <tr>
        <td><%= registration_form_niki.name %></td>
        <td><%= registration_form_niki.phone %></td>
        <td><%= link_to 'Show', registration_form_niki %></td>
        <td><%= link_to 'Edit', edit_registration_form_niki_path(registration_form_niki) %></td>
        <td><%= link_to 'Destroy', registration_form_niki, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registration Form Niki', new_registration_form_niki_path %>

app/views/registration_form_nikis/new.html.erb
<h1>New Registration Form Niki</h1>

<%= render 'form', registration_form_niki: @registration_form_niki %>

<%= link_to 'Back', registration_form_nikis_path %>

app/views/registration_form_nikis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @registration_form_niki.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @registration_form_niki.phone %>
</p>

<%= link_to 'Edit', edit_registration_form_niki_path(@registration_form_niki) %> |
<%= link_to 'Back', registration_form_nikis_path %>