config/routes.rb
Rails.application.routes.draw do
  resources :registration_form1s
  resources :registration_form_nikis
  resources :registration_formtests
  resources :registration_form_test_abcs
  resources :registration_forms
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/controllers/registration_forms_controller.rb
class RegistrationFormsController < ApplicationController
  before_action :set_registration_form, only: [:show, :edit, :update, :destroy]

  # GET /registration_forms
  # GET /registration_forms.json
  def index
    @registration_forms = RegistrationForm.all
  end

  # GET /registration_forms/1
  # GET /registration_forms/1.json
  def show
  end

  # GET /registration_forms/new
  def new
    @registration_form = RegistrationForm.new
  end

  # GET /registration_forms/1/edit
  def edit
  end

  # POST /registration_forms
  # POST /registration_forms.json
  def create
    @registration_form = RegistrationForm.new(registration_form_params)

    respond_to do |format|
      if @registration_form.save
        format.html { redirect_to @registration_form, notice: 'Registration form was successfully created.' }
        format.json { render :show, status: :created, location: @registration_form }
      else
        format.html { render :new }
        format.json { render json: @registration_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registration_forms/1
  # PATCH/PUT /registration_forms/1.json
  def update
    respond_to do |format|
      if @registration_form.update(registration_form_params)
        format.html { redirect_to @registration_form, notice: 'Registration form was successfully updated.' }
        format.json { render :show, status: :ok, location: @registration_form }
      else
        format.html { render :edit }
        format.json { render json: @registration_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registration_forms/1
  # DELETE /registration_forms/1.json
  def destroy
    @registration_form.destroy
    respond_to do |format|
      format.html { redirect_to registration_forms_url, notice: 'Registration form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registration_form
      @registration_form = RegistrationForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registration_form_params
      params.require(:registration_form).permit(:name, :phone)
    end
end

app/helpers/registration_forms_helper.rb
module RegistrationFormsHelper
end

app/views/registration_forms/_form.html.erb
<%= form_with(model: registration_form, local: true) do |form| %>
  <% if registration_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(registration_form.errors.count, "error") %> prohibited this registration_form from being saved:</h2>

      <ul>
      <% registration_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/registration_forms/edit.html.erb
<h1>Editing Registration Form</h1>

<%= render 'form', registration_form: @registration_form %>

<%= link_to 'Show', @registration_form %> |
<%= link_to 'Back', registration_forms_path %>

app/views/registration_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registration Forms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registration_forms.each do |registration_form| %>
      <tr>
        <td><%= registration_form.name %></td>
        <td><%= registration_form.phone %></td>
        <td><%= link_to 'Show', registration_form %></td>
        <td><%= link_to 'Edit', edit_registration_form_path(registration_form) %></td>
        <td><%= link_to 'Destroy', registration_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registration Form', new_registration_form_path %>

app/views/registration_forms/new.html.erb
<h1>New Registration Form</h1>

<%= render 'form', registration_form: @registration_form %>

<%= link_to 'Back', registration_forms_path %>

app/views/registration_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @registration_form.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @registration_form.phone %>
</p>

<%= link_to 'Edit', edit_registration_form_path(@registration_form) %> |
<%= link_to 'Back', registration_forms_path %>